name: "test workflow"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          path: myfolder
      - name: "List files in myfolder"
        run: |
           cd myfolder && ls -lhrt
      - name: "Run tests"
        run: |  
            cd myfolder && echo "Running tests..." 
            python -m unittest discover -s tests
        
