name: "test workflow"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: |
          actions/checkout@v2 myfolder
      - name: "List files in myfolder"
        run: |
           cd myfolder && ls -lhrt
