name: "test workflow"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        run: |
          echo "Checking out code..."
          echo "Github context: ${{ toJson(github) }}"
          git clone https://github.com/${{ github.repository }}.git myfolder
          cd myfolder && ls -lhrt
